/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankingsys;

/**
 *
 * @author Rudraksha
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
public class AdminOperation extends javax.swing.JFrame {

    /**
     * Creates new form AdminOperation
     */
    public AdminOperation() {
        initComponents();
        lblacccno.setVisible(false);
        pnlcust.setVisible(false);
        btndelete.setVisible(false);
        pnlloan.setVisible(false);
        btnapprove.setVisible(false);
        btnreject.setVisible(false);
       
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BankSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BankSystemPU").createEntityManager();
        customerinfoQuery = java.beans.Beans.isDesignTime() ? null : BankSystemPUEntityManager.createQuery("SELECT c FROM Customerinfo c");
        customerinfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customerinfoQuery.getResultList();
        loaninfoQuery = java.beans.Beans.isDesignTime() ? null : BankSystemPUEntityManager.createQuery("SELECT l FROM Loaninfo l");
        loaninfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : loaninfoQuery.getResultList();
        customerinfoQuery1 = java.beans.Beans.isDesignTime() ? null : BankSystemPUEntityManager.createQuery("SELECT c FROM Customerinfo c");
        customerinfoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customerinfoQuery1.getResultList();
        customerinfoQuery2 = java.beans.Beans.isDesignTime() ? null : BankSystemPUEntityManager.createQuery("SELECT c FROM Customerinfo c");
        customerinfoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customerinfoQuery2.getResultList();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblacccno = new javax.swing.JLabel();
        cboperation = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnapprove = new javax.swing.JButton();
        btnreject = new javax.swing.JButton();
        pnlcust = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        pnlloan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblloan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(new java.awt.Color(51, 51, 255));
        btnback.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, -1, -1));

        btndelete.setBackground(new java.awt.Color(51, 51, 255));
        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ADMIN OPERATIONS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 906, -1));
        jPanel1.add(lblacccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 40, 10));

        cboperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Operation--", "Customer's Information", "Loan Information" }));
        cboperation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboperationItemStateChanged(evt);
            }
        });
        jPanel1.add(cboperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setText("Select Information to View :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 20));

        btnapprove.setBackground(new java.awt.Color(51, 51, 255));
        btnapprove.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnapprove.setForeground(new java.awt.Color(255, 255, 255));
        btnapprove.setText("APPROVE");
        btnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapproveActionPerformed(evt);
            }
        });
        jPanel1.add(btnapprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, -1));

        btnreject.setBackground(new java.awt.Color(51, 51, 255));
        btnreject.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnreject.setForeground(new java.awt.Color(255, 255, 255));
        btnreject.setText("REJECT");
        btnreject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrejectActionPerformed(evt);
            }
        });
        jPanel1.add(btnreject, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        pnlcust.setBackground(new java.awt.Color(51, 255, 255));

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accno", "Fname", "Lname", "Gender", "Age", "Contactno", "Emailid", "Username", "Password", "Address", "Aadharno", "Pancardno", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customerinfoList2, tbldata);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${accno}"));
        columnBinding.setColumnName("Accno");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fname}"));
        columnBinding.setColumnName("Fname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lname}"));
        columnBinding.setColumnName("Lname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${gender}"));
        columnBinding.setColumnName("Gender");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${age}"));
        columnBinding.setColumnName("Age");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${contactno}"));
        columnBinding.setColumnName("Contactno");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailid}"));
        columnBinding.setColumnName("Emailid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${username}"));
        columnBinding.setColumnName("Username");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${password}"));
        columnBinding.setColumnName("Password");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${aadharno}"));
        columnBinding.setColumnName("Aadharno");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pancardno}"));
        columnBinding.setColumnName("Pancardno");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${amount}"));
        columnBinding.setColumnName("Amount");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tbldata);

        javax.swing.GroupLayout pnlcustLayout = new javax.swing.GroupLayout(pnlcust);
        pnlcust.setLayout(pnlcustLayout);
        pnlcustLayout.setHorizontalGroup(
            pnlcustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        pnlcustLayout.setVerticalGroup(
            pnlcustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(pnlcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 880, 60));

        pnlloan.setBackground(new java.awt.Color(51, 255, 255));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, loaninfoList, tblloan);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${accno}"));
        columnBinding.setColumnName("Accno");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fname}"));
        columnBinding.setColumnName("Fname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailid}"));
        columnBinding.setColumnName("Emailid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${amount}"));
        columnBinding.setColumnName("Amount");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${password}"));
        columnBinding.setColumnName("Password");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pancardno}"));
        columnBinding.setColumnName("Pancardno");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(tblloan);

        javax.swing.GroupLayout pnlloanLayout = new javax.swing.GroupLayout(pnlloan);
        pnlloan.setLayout(pnlloanLayout);
        pnlloanLayout.setHorizontalGroup(
            pnlloanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        pnlloanLayout.setVerticalGroup(
            pnlloanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(pnlloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 880, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        HomePage hp = new HomePage();
        hp.show();
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int row = tbldata.getSelectedRow();

        String selected = tbldata.getModel().getValueAt(row, 0).toString();//accno
        String emailid = tbldata.getModel().getValueAt(row, 6).toString();//emailid
        if(row>=0){
            //tblmodel.removeRow(row);
            //((DefaultTableModel)tbldata.getModel()).removeRow(row);
            try {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
                Connection cn = DriverManager.getConnection("jdbc:derby://localhost:1527/BankSystem");
                String qry = "delete from customerinfo where accno = "+selected+"";
                PreparedStatement pst=cn.prepareStatement(qry);
                int ch = pst.executeUpdate();
                if(ch==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"Account Deleted Successfully..!!");
                    String ToEmail = emailid;
                    String FromEmail = "infoprojectemail2@gmail.com";
                    String FromEmailPassword = "#cec@mvlu";//My Password
                    String Subject = "Your Account was Deleted.";

                    Properties properties = new Properties();
                    properties.put("mail.smtp.auth","true");
                    properties.put("mail.smtp.starttls.enable","true");
                    properties.put("mail.smtp.host","smtp.gmail.com");
                    properties.put("mail.smtp.port","587");

                    Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication()
                        {
                            return new PasswordAuthentication(FromEmail, FromEmailPassword);
                        }
                    })  ;

                    try {
                        MimeMessage message = new MimeMessage(session);
                        message.setFrom(new InternetAddress(FromEmail));
                        //message.addRecipients(Message.RecipientType.TO, new InternetAddress(ToEmail));
                        message.addRecipients(Message.RecipientType.TO,InternetAddress.parse(ToEmail));
                        message.setSubject(Subject);
                        message.setText("Your A/c"+selected+" has been deleted successfully . ");
                        Transport.send(message);
                    }       catch (Exception e) {System.out.println(e+"Error Occurred");}
                }
                else{JOptionPane.showMessageDialog(rootPane,"Sorry,Account not Deleted");}
                cn.close();
            } catch (Exception e) {JOptionPane.showMessageDialog(null,e,"Error Message",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void cboperationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboperationItemStateChanged
        String option = cboperation.getSelectedItem().toString();
       if(option.equalsIgnoreCase("--Select Operation--")){
            pnlcust.setVisible(false);
            pnlloan.setVisible(false);
            btndelete.setVisible(false);
            btnapprove.setVisible(false);
            btnreject.setVisible(false);
        }
       else if(option.equalsIgnoreCase("Customer's Information")){
           pnlcust.setVisible(true);
            pnlloan.setVisible(false);
            btndelete.setVisible(true);
            btnapprove.setVisible(false);
            btnreject.setVisible(false);
        }
        else if(option.equalsIgnoreCase("Loan Information")){
            pnlcust.setVisible(false);
            pnlloan.setVisible(true);
            btndelete.setVisible(false);
            btnapprove.setVisible(true);
            btnreject.setVisible(true);
        }
    }//GEN-LAST:event_cboperationItemStateChanged

    private void btnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapproveActionPerformed
         int row = tblloan.getSelectedRow();

        String selected = tblloan.getModel().getValueAt(row, 0).toString();//accno
        String emailid = tblloan.getModel().getValueAt(row, 2).toString();//emailid
        String amount = tblloan.getModel().getValueAt(row, 3).toString();//amount
        if(row>=0){
            //tblmodel.removeRow(row);
            //((DefaultTableModel)tbldata.getModel()).removeRow(row);
            try {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
                Connection cn = DriverManager.getConnection("jdbc:derby://localhost:1527/BankSystem");
                String qry = "update loaninfo set status = ? where accno = "+selected+"";
                PreparedStatement pst=cn.prepareStatement(qry);
                pst.setString(1,"Approved");
                int ch = pst.executeUpdate();
                if(ch==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"Loan Approved..!!");
                    String ToEmail = emailid;
                    String FromEmail = "infoprojectemail2@gmail.com";
                    String FromEmailPassword = "#cec@mvlu";//My Password
                    String Subject = "Your Loan was Approved.";

                    Properties properties = new Properties();
                    properties.put("mail.smtp.auth","true");
                    properties.put("mail.smtp.starttls.enable","true");
                    properties.put("mail.smtp.host","smtp.gmail.com");
                    properties.put("mail.smtp.port","587");

                    Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication()
                        {
                            return new PasswordAuthentication(FromEmail, FromEmailPassword);
                        }
                    })  ;

                    try {
                        MimeMessage message = new MimeMessage(session);
                        message.setFrom(new InternetAddress(FromEmail));
                        //message.addRecipients(Message.RecipientType.TO, new InternetAddress(ToEmail));
                        message.addRecipients(Message.RecipientType.TO,InternetAddress.parse(ToEmail));
                        message.setSubject(Subject);
                        message.setText("Your Loan of Rs. "+amount+" for A/c "+selected+" has been approved. ");
                        Transport.send(message);
                    }       catch (Exception e) {System.out.println(e+"Error Occurred");}
                }
                else{JOptionPane.showMessageDialog(rootPane,"Sorry,Loan not Approved");}
                cn.close();
            } catch (Exception e) {JOptionPane.showMessageDialog(null,e,"Error Message",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnapproveActionPerformed

    private void btnrejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrejectActionPerformed
         int row = tblloan.getSelectedRow();

        String selected = tblloan.getModel().getValueAt(row, 0).toString();//accno
        String emailid = tblloan.getModel().getValueAt(row, 2).toString();//emailid
        String amount = tblloan.getModel().getValueAt(row, 3).toString();//amount
        if(row>=0){
            //tblmodel.removeRow(row);
            //((DefaultTableModel)tbldata.getModel()).removeRow(row);
            try {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
                Connection cn = DriverManager.getConnection("jdbc:derby://localhost:1527/BankSystem");
                String qry = "update loaninfo set status = ? where accno = "+selected+"";
                PreparedStatement pst=cn.prepareStatement(qry);
                pst.setString(1,"Rejected");
                int ch = pst.executeUpdate();
                if(ch==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"Loan Rejected..!!");
                    String ToEmail = emailid;
                    String FromEmail = "infoprojectemail2@gmail.com";
                    String FromEmailPassword = "#cec@mvlu";//My Password
                    String Subject = "Your Loan was Approved.";

                    Properties properties = new Properties();
                    properties.put("mail.smtp.auth","true");
                    properties.put("mail.smtp.starttls.enable","true");
                    properties.put("mail.smtp.host","smtp.gmail.com");
                    properties.put("mail.smtp.port","587");

                    Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication()
                        {
                            return new PasswordAuthentication(FromEmail, FromEmailPassword);
                        }
                    })  ;

                    try {
                        MimeMessage message = new MimeMessage(session);
                        message.setFrom(new InternetAddress(FromEmail));
                        //message.addRecipients(Message.RecipientType.TO, new InternetAddress(ToEmail));
                        message.addRecipients(Message.RecipientType.TO,InternetAddress.parse(ToEmail));
                        message.setSubject(Subject);
                        message.setText("Your Loan of Rs. "+amount+" for A/c "+selected+" has been rejected. ");
                        Transport.send(message);
                    }       catch (Exception e) {System.out.println(e+"Error Occurred");}
                }
                else{JOptionPane.showMessageDialog(rootPane,"Sorry,Loan not Rejected");}
                cn.close();
            } catch (Exception e) {JOptionPane.showMessageDialog(null,e,"Error Message",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnrejectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BankSystemPUEntityManager;
    private javax.swing.JButton btnapprove;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreject;
    private javax.swing.JComboBox<String> cboperation;
    private java.util.List<bankingsys.Customerinfo> customerinfoList;
    private java.util.List<bankingsys.Customerinfo> customerinfoList1;
    private java.util.List<bankingsys.Customerinfo> customerinfoList2;
    private javax.persistence.Query customerinfoQuery;
    private javax.persistence.Query customerinfoQuery1;
    private javax.persistence.Query customerinfoQuery2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblacccno;
    private java.util.List<bankingsys.Loaninfo> loaninfoList;
    private javax.persistence.Query loaninfoQuery;
    private javax.swing.JPanel pnlcust;
    private javax.swing.JPanel pnlloan;
    private javax.swing.JTable tbldata;
    private javax.swing.JTable tblloan;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
