/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankingsys;

/**
 *
 * @author Rudraksha
 */
import java.sql.*;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
public class UsersProfile extends javax.swing.JFrame {

    /**
     * Creates new form UsersProfile
     */
    public UsersProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        lblfname = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        lbllname = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblcno = new javax.swing.JLabel();
        txtcontactno = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lblpasswd = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        lbladdress = new javax.swing.JLabel();
        lblaadharno = new javax.swing.JLabel();
        txtaadharnum = new javax.swing.JTextField();
        lblpannum = new javax.swing.JLabel();
        txtpannum = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        lblacno = new javax.swing.JLabel();
        lblaccno = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" USER PROFILE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setText("Enter Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 65, 122, 27));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel3.setText("Enter Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 123, 122, 26));
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 66, 150, 27));

        btnback.setBackground(new java.awt.Color(51, 51, 255));
        btnback.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 497, -1, -1));

        btnclear.setBackground(new java.awt.Color(51, 51, 255));
        btnclear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR ALL");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 167, -1, -1));

        btnsubmit.setBackground(new java.awt.Color(51, 51, 255));
        btnsubmit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 167, -1, -1));

        lblfname.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblfname.setText("Enter First-Name :");
        jPanel1.add(lblfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 20));

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 239, 140, -1));

        lbllname.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbllname.setText("Enter Last-Name :");
        jPanel1.add(lbllname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 20));
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 277, 140, -1));

        lblgender.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblgender.setText("Enter Gender :");
        jPanel1.add(lblgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 324, 120, 20));
        jPanel1.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 323, 140, -1));

        lblage.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblage.setText("Enter Age :");
        jPanel1.add(lblage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 374, 120, 20));
        jPanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 372, 140, -1));

        lblcno.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblcno.setText("Enter Contact No :");
        jPanel1.add(lblcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 120, 20));
        jPanel1.add(txtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, -1));

        lblemail.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblemail.setText("Enter Email-ID :");
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 464, 120, 20));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 465, 140, -1));

        lblusername.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblusername.setText("Enter Username :");
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 150, 20));

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 190, -1));

        lblpasswd.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblpasswd.setText("Enter Password :");
        jPanel1.add(lblpasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 150, 20));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 190, -1));

        lbladdress.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbladdress.setText("Enter Address :");
        jPanel1.add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 150, 20));

        lblaadharno.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblaadharno.setText("Enter AadharNo :");
        jPanel1.add(lblaadharno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 150, 20));
        jPanel1.add(txtaadharnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 190, -1));

        lblpannum.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblpannum.setText("Enter PAN Card no :");
        jPanel1.add(lblpannum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 150, 20));
        jPanel1.add(txtpannum, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 190, -1));

        btnupdate.setBackground(new java.awt.Color(51, 51, 255));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 497, -1, -1));

        lblacno.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblacno.setText("Account No :");
        jPanel1.add(lblacno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, 20));

        lblaccno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lblaccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 130, 20));
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 190, -1));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        HomePage hp = new HomePage();
        hp.show();
        dispose();

    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtuname.setText("");
        txtpass.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String fname,lname,gender,emailid,username,password,address,contactno,aadharnum,pannum;
        int age,accno;
        String uname=txtuname.getText(),pass=txtpass.getText();
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection cn = DriverManager.getConnection("jdbc:derby://localhost:1527/BankSystem");
            Statement st = cn.createStatement();
            String qry = "select * from customerinfo where username = '"+uname+"' and password = '"+pass+"'";
            ResultSet rs = st.executeQuery(qry);
            if(rs.next()){
                JOptionPane.showMessageDialog(rootPane,"Record Found..!!");

                txtfname.setVisible(true);
                txtlname.setVisible(true);
                txtgender.setVisible(true);
                txtage.setVisible(true);
                txtcontactno.setVisible(true);
                txtemail.setVisible(true);
                txtusername.setVisible(true);
                txtpassword.setVisible(true);
                txtaddress.setVisible(true);
                txtaadharnum.setVisible(true);
                txtpannum.setVisible(true);
                lblaccno.setVisible(true);
                lblfname.setVisible(true);
                lbllname.setVisible(true);
                lblgender.setVisible(true);
                lblage.setVisible(true);
                lblcno.setVisible(true);
                lblemail.setVisible(true);
                lblusername.setVisible(true);
                lblpasswd.setVisible(true);
                lbladdress.setVisible(true);
                lblaadharno.setVisible(true);
                lblpannum.setVisible(true);
                btnupdate.setVisible(true);
                btnback.setVisible(true);
                lblacno.setVisible(true);

                accno = rs.getInt(1);
                fname = rs.getString(2);
                lname = rs.getString(3);
                gender = rs.getString(4);
                age = rs.getInt(5);
                contactno = rs.getString(6);
                emailid = rs.getString(7);
                username = rs.getString(8);
                password = rs.getString(9);
                address = rs.getString(10);
                aadharnum = rs.getString(11);
                pannum = rs.getString(12);

                lblaccno.setText(String.valueOf(accno));
                txtfname.setText(fname);
                txtlname.setText(lname);
                txtgender.setText(gender);
                txtage.setText(String.valueOf(age));
                txtcontactno.setText(contactno);
                txtemail.setText(emailid);
                txtusername.setText(username);
                txtpassword.setText(password);
                txtaddress.setText(address);
                txtaadharnum.setText(aadharnum);
                txtpannum.setText(pannum);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Sorry,wrong Username or Password,Try Again..!!");
            }

        } catch (Exception e)
        { JOptionPane.showMessageDialog(null,e,"Error Message",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String fname,lname,gender,emailid,username,password,address,contactno,aadharnum,pannum;
        int age,accno;

        accno=Integer.parseInt(lblaccno.getText());
        fname=txtfname.getText();
        lname=txtlname.getText();
        gender = txtgender.getText();
        emailid=txtemail.getText();
        username=txtusername.getText();
        password=txtpassword.getText();
        address=txtaddress.getText();
        age=Integer.parseInt(txtage.getText());
        contactno=txtcontactno.getText();
        aadharnum=txtaadharnum.getText();
        pannum=txtpannum.getText();
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection cn = DriverManager.getConnection("jdbc:derby://localhost:1527/BankSystem");
            Statement st = cn.createStatement();
            String qry ="update customerinfo set fname = '"+fname+"',lname='"+lname+"',gender='"+gender+"',age="+age+",contactno='"+contactno+"',emailid='"+emailid+"',username='"+username+"',password='"+password+"',address='"+address+"',aadharno='"+aadharnum+"',pancardno='"+pannum+"' where accno = "+accno+"";
            int ch = st.executeUpdate(qry);
            if(ch==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Account Updated Successfully..!!");
                String ToEmail = emailid;
                String FromEmail = "infoprojectemail2@gmail.com";
                String FromEmailPassword = "#cec@mvlu";//My Password
                String Subject = "Your Account was Updated.";

                Properties properties = new Properties();
                properties.put("mail.smtp.auth","true");
                properties.put("mail.smtp.starttls.enable","true");
                properties.put("mail.smtp.host","smtp.gmail.com");
                properties.put("mail.smtp.port","587");

                Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication()
                    {
                        return new PasswordAuthentication(FromEmail, FromEmailPassword);
                    }
                })  ;

                try {
                    MimeMessage message = new MimeMessage(session);
                    message.setFrom(new InternetAddress(FromEmail));
                    //message.addRecipients(Message.RecipientType.TO, new InternetAddress(ToEmail));
                    message.addRecipients(Message.RecipientType.TO,InternetAddress.parse(ToEmail));
                    message.setSubject(Subject);
                    message.setText("Your A/c"+accno+" has been updated as per your given information."
                        + "\nVisit Banking System application to view details. ");
                    Transport.send(message);
                }       catch (Exception e) {System.out.println(e+"Error Occurred");}
            }
            else{JOptionPane.showMessageDialog(rootPane,"Sorry,Account not Updated");}
            cn.close();
        } catch (Exception e) {JOptionPane.showMessageDialog(null,e,"Error Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblaadharno;
    private javax.swing.JLabel lblaccno;
    private javax.swing.JLabel lblacno;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcno;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblpannum;
    private javax.swing.JLabel lblpasswd;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtaadharnum;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtpannum;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtuname;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
